### PR TITLE
ML-DSA: Moved all the encoding code and more of the arithmetic code to a vectorized structure.

### PR DESCRIPTION
**Pull request by xvzcf**
- hints are now represented using `i32`s instead of `bool`s.

### CODE REVIEW

**Review by franziskuskiefer — COMMENTED** [review]
lgtm

But I'm getting an unused function warning for `from_i32_array`. I thought I asked to suppress that in a previous PR?

**Comment by xvzcf** [comment]
> lgtm
> 
> But I'm getting an unused function warning for `from_i32_array`. I thought I asked to suppress that in a previous PR?

I did [here](https://github.com/cryspen/libcrux/blob/goutam/ml-dsa-more-vectorizing/libcrux-ml-dsa/src/polynomial.rs#L55), and I'm not getting that warning. Are you getting it from `libcrux-ml-dsa/src/polynomial.rs`?

**Comment by franziskuskiefer** [comment]
> I did [here](https://github.com/cryspen/libcrux/blob/goutam/ml-dsa-more-vectorizing/libcrux-ml-dsa/src/polynomial.rs#L55), and I'm not getting that warning. Are you getting it from `libcrux-ml-dsa/src/polynomial.rs`?

Oh, you re-used the branch 😬 that's why I was on an old version. Please try not to do that.

**Review by franziskuskiefer — APPROVED** [review]

**Comment by xvzcf** [comment]
> Oh, you re-used the branch 😬 that's why I was on an old version. Please try not to do that.

Noted.

**Pull request merged**
