### PR TITLE
kyber crate extraction script

### PR DESCRIPTION
**Pull request by franziskuskiefer**
A simple shell script to pull out kyber as a separate crate for Aeneas.

cc @protz

### CODE REVIEW

**Comment by xvzcf** [comment]
When running the script I get

```
fixing up src/PERFORMANCE.md ...
sed: 1: "src/PERFORMANCE.md": unterminated substitute pattern
```

speaking of which, I need to start regularly updating this file with every PR again ...

**Comment by franziskuskiefer** [comment]
> When running the script I get

hm, do you use mac `sed`? `gsed` should be able to handle this. I didn't want to make this more complex than necessary ...

> speaking of which, I need to start regularly updating this file with every PR again ...

Yeah we should update the numbers from time to time....

**Comment by xvzcf** [comment]
> > When running the script I get
> 
> hm, do you use mac `sed`? `gsed` should be able to handle this. I didn't want to make this more complex than necessary ...

Yeah, I used `gsed` and it worked. We can just leave the script as is since it's temporary.

**Comment by franziskuskiefer** [comment]
> Yeah, I used `gsed` and it worked. We can just leave the script as is since it's temporary.

Yes, we should delete this as soon as it's not needed anymore.

**Review by xvzcf — APPROVED** [review]
This is fine with me, I'll wait for Jonathan to approve.

**Pull request merged**
