### PR TITLE
Add proofs for portable compress module

### PR DESCRIPTION
**Pull request by mamonet**
This PR add full proofs for portable compress functions, the proofs support the new refined integers and it depend on the following hax branch https://github.com/hacspec/hax/tree/refined-ints-neg

### CODE REVIEW

**Comment by karthikbhargavan** [comment]
Can you make this work without the refined-ints branch? That would make it easier to merge.

**Comment by mamonet** [comment]
I can, but then we have to modify the code to support refined integers when `experiment-refined-ints` is merged for some changes like using `mk_i16`..

**Comment by karthikbhargavan** [comment]
yes, so you can merge those changes into experiment-refined-ints, but the portable-compress could go straight into dev...

**Comment by franziskuskiefer** [comment]
@karthikbhargavan @mamonet what's the state of this?

**Comment by mamonet** [comment]
The changes made it to dev branch, I think we can close this PR.

**Pull request closed without merging**
