### PR TITLE
Proofs misc setup improvements

### PR DESCRIPTION
**Pull request by W95Psp**
This PR has a bunch of improvements for the F* setup.
 - It's using the new Makefile I wrote for the tutorial, and that I improved yesterday evening for sandbox. Now F* caching is project-wide and should work.
 - Use only one dependency, workspace-wide, to hax-lib, so that we can actually run `cargo update hax-lib`
 - put the makefile at one place, and have proxy makefiles that just include them

### CODE REVIEW

**Comment by mamonet** [comment]
The output layout is much better, and rebuilding now starts where it left off.

**Review by mamonet — APPROVED** [review]

**Comment by W95Psp** [comment]
Seems like this was merged into https://github.com/cryspen/libcrux/pull/475

**Comment by karthikbhargavan** [comment]
https://github.com/cryspen/libcrux/pull/475 is now merged.
Could you check if there were some changes here that did not make it into that PR?
Otherwise, let's close this.

**Comment by W95Psp** [comment]
Nice, let's close this, there are a few thing, gonna make another PR

**Pull request closed without merging**
