### PR TITLE
A more complete spec of ML-KEM

### PR DESCRIPTION
**Pull request by karthikbhargavan**
This PR fills out some of the functions of the ML-KEM spec that had not been previously specified and does a general clean up of the spec in prep for the proofs.

### CODE REVIEW

**Comment by karthikbhargavan** [comment]
This is blocked on ind_cca decap breaking CI. We need to debug this.

**Comment by karthikbhargavan** [comment]
This now relies on https://github.com/hacspec/hax/pull/854

**Comment by karthikbhargavan** [comment]
Fixed decap using https://github.com/hacspec/hax/pull/854

**Comment by W95Psp** [comment]
Should we merge this, now https://github.com/hacspec/hax/pull/856 is in (aka unsize are gone)?

**Pull request merged**
